global.money = 10;
global.diary = false;
global.dialog_end = 1;
global.shop = false;
global.battle = false;
//global.LANGUAGE = "eng"; // Mazur
global.certificate =0;
hit_cher=0;
global.gameStart = 0;
global.item_bought = false;
