seq_buses = 0;
//bus_position = 0;
busX = 0;
busY = 0;
bus = 1;
mp_open = 0;
start = true;
//alarm[0] = 1;
show_debug_message("create_bus");
show_debug_message("create_bus");
show_debug_message("create_bus");
show_debug_message("create_bus");
show_debug_message("create_bus");
show_debug_message("create_bus");
show_debug_message("create_bus");
show_debug_message("create_bus");